[package]
name = "pwsf"
version = "0.1.0"
authors = ["Stanislav Fomichev <kernel@fomichev.me>"]

[dependencies]
byteorder = "1"
lazy_static = "0.2"

[dependencies.gcrypt]
version = "0.5"
default-features = false
features = ["nightly"]
